"""

Revision ID: 050f1664c707
Revises:
Create Date: 2024-04-04 21:34:05.159354

"""


# revision identifiers, used by Alembic.
revision = "050f1664c707"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
