"""

Revision ID: 06dd532d897a
Revises:
Create Date: 2024-04-01 18:39:14.879886

"""
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "06dd532d897a"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chatrequest",
        sa.Column("phone_number", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("request_date", sa.DateTime(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("requester_uuid", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("receiver_uuid", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["receiver_uuid"],
            ["user.uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["requester_uuid"],
            ["user.uuid"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_chatrequest_phone_number"), "chatrequest", ["phone_number"], unique=False)
    op.create_index(op.f("ix_chatrequest_status"), "chatrequest", ["status"], unique=False)
    op.drop_table("friend")
    op.drop_table("friendrequest")
    op.add_column("user", sa.Column("first_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column("user", sa.Column("last_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_index("ix_user_username", table_name="user")
    op.create_index(op.f("ix_user_first_name"), "user", ["first_name"], unique=False)
    op.create_index(op.f("ix_user_last_name"), "user", ["last_name"], unique=False)
    op.drop_column("user", "username")
    op.drop_column("user", "fullname")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("fullname", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column("user", sa.Column("username", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f("ix_user_last_name"), table_name="user")
    op.drop_index(op.f("ix_user_first_name"), table_name="user")
    op.create_index("ix_user_username", "user", ["username"], unique=False)
    op.drop_column("user", "last_name")
    op.drop_column("user", "first_name")
    op.create_table(
        "friendrequest",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_uuid", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("friend_uuid", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("request_date", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column("status", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(["friend_uuid"], ["user.uuid"], name="friendrequest_friend_uuid_fkey"),
        sa.ForeignKeyConstraint(["user_uuid"], ["user.uuid"], name="friendrequest_user_uuid_fkey"),
        sa.PrimaryKeyConstraint("id", name="friendrequest_pkey"),
    )
    op.create_table(
        "friend",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_uuid", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("friend_uuid", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("friendship_date", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column("status", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(["friend_uuid"], ["user.uuid"], name="friend_friend_uuid_fkey"),
        sa.ForeignKeyConstraint(["user_uuid"], ["user.uuid"], name="friend_user_uuid_fkey"),
        sa.PrimaryKeyConstraint("id", name="friend_pkey"),
    )
    op.drop_index(op.f("ix_chatrequest_status"), table_name="chatrequest")
    op.drop_index(op.f("ix_chatrequest_phone_number"), table_name="chatrequest")
    op.drop_table("chatrequest")
    # ### end Alembic commands ###
