"""

Revision ID: 11e5fcb51242
Revises:
Create Date: 2024-03-28 12:34:31.739292

"""
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "11e5fcb51242"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("property", sa.Column("search_result_uuid", sqlmodel.sql.sqltypes.GUID(), nullable=False))
    op.create_foreign_key(None, "property", "searchresult", ["search_result_uuid"], ["uuid"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "property", type_="foreignkey")
    op.drop_column("property", "search_result_uuid")
    # ### end Alembic commands ###
