"""

Revision ID: 54dad786c6ee
Revises: 6772186dd453
Create Date: 2024-04-05 13:52:02.504993

"""


# revision identifiers, used by Alembic.
revision = "54dad786c6ee"
down_revision = "6772186dd453"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
