"""init

Revision ID: 5a9e723b76f4
Revises:
Create Date: 2024-02-10 23:28:05.686285

"""


# revision identifiers, used by Alembic.
revision = "5a9e723b76f4"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
