"""

Revision ID: 61c8a292eaba
Revises:
Create Date: 2024-08-16 22:26:30.648565

"""
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "61c8a292eaba"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "authcode",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(length=400), nullable=False),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("request_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("request_date", sa.DateTime(), nullable=False),
        sa.Column("expire_date", sa.DateTime(), nullable=False),
        sa.Column("usage_date", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_authcode_email"), "authcode", ["email"], unique=False)
    op.create_index(op.f("ix_authcode_request_type"), "authcode", ["request_type"], unique=False)
    op.create_index(op.f("ix_authcode_status"), "authcode", ["status"], unique=False)
    op.create_table(
        "user",
        sa.Column("join_date", sa.DateTime(), nullable=False),
        sa.Column("provider", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("profile_picture", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(length=400), nullable=False),
        sa.Column("first_name", sqlmodel.sql.sqltypes.AutoString(length=700), nullable=True),
        sa.Column("last_name", sqlmodel.sql.sqltypes.AutoString(length=700), nullable=True),
        sa.Column("account_view", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_sidebar_open", sa.Boolean(), nullable=False),
        sa.Column("disabled", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("hashed_password", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("refresh_token", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("uuid"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=False)
    op.create_index(op.f("ix_user_first_name"), "user", ["first_name"], unique=False)
    op.create_index(op.f("ix_user_last_name"), "user", ["last_name"], unique=False)
    op.create_index(op.f("ix_user_provider"), "user", ["provider"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_provider"), table_name="user")
    op.drop_index(op.f("ix_user_last_name"), table_name="user")
    op.drop_index(op.f("ix_user_first_name"), table_name="user")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_authcode_status"), table_name="authcode")
    op.drop_index(op.f("ix_authcode_request_type"), table_name="authcode")
    op.drop_index(op.f("ix_authcode_email"), table_name="authcode")
    op.drop_table("authcode")
    # ### end Alembic commands ###
