"""

Revision ID: 6772186dd453
Revises: 050f1664c707
Create Date: 2024-04-05 11:17:20.887942

"""


# revision identifiers, used by Alembic.
revision = "6772186dd453"
down_revision = "050f1664c707"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
