"""

Revision ID: a44792a0b0f9
Revises:
Create Date: 2024-04-12 22:32:23.409440

"""


# revision identifiers, used by Alembic.
revision = "a44792a0b0f9"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
