"""

Revision ID: eb04e2bdf497
Revises:
Create Date: 2024-04-26 10:56:11.529651

"""


# revision identifiers, used by Alembic.
revision = "eb04e2bdf497"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
