"""

Revision ID: ef12e473f451
Revises:
Create Date: 2024-08-04 11:38:34.089469

"""


# revision identifiers, used by Alembic.
revision = "ef12e473f451"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
