"""

Revision ID: f5b9305d8655
Revises:
Create Date: 2024-04-04 15:19:08.240520

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f5b9305d8655"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "email", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("user", "first_name", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("user", "last_name", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("user", "account_view", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("user", "is_sidebar_open", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column("user", "disabled", existing_type=sa.BOOLEAN(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "disabled", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column("user", "is_sidebar_open", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column("user", "account_view", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("user", "last_name", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("user", "first_name", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("user", "email", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###
